### ISSUE TITLE
error with fitting essim_glm

### ISSUE THREAD

**Issue by jakeberv** [MatthewOM/ES-sim-GLM#1]
Hi there,
I am doing some testing with ES-SIM GLM, and I am running into an error:

```
Error in glm(is ~ trait1 + trait2, family = gaussian, method = "glm.fit") : 
  'family' not recognized
Called from: glm(is ~ trait1 + trait2, family = gaussian, method = "glm.fit")
```

Is there some package dependency required here? I tried loading the packages noted in the the other scripts-- eg, ape, mvtnorm, caper, diversitree, but this does not seem to resolve the issue. Any idea?

**Comment by jakeberv** [comment]
ah, nevermind. i think i figured it out. it was calling gaussian from some other package i had loaded.

**Comment by MatthewOM** [comment]
Hi there,

Sorry for the late reply. Glad you were able to troubleshoot this.

All the best,
Matthew
